### ISSUE TITLE
add a subtitle for patient notes tab

### ISSUE THREAD

**Issue by ph1l** [ocemr/ocemr#10]
<a href="https://github.com/ph1l"><img src="https://avatars3.githubusercontent.com/u/39502?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ph1l](https://github.com/ph1l)**
_Mon Aug 13 16:49:35 2018_
_Originally opened as https://github.com/ph1l/ocemr/issues/55_

----

from @kzcbum : 

> ie. "this tab is for internal communication only, does not print out on patient's visit notes." ?

related to https://github.com/ph1l/ocemr/issues/19

**Comment by patfreeman** [comment]
actually relates to https://github.com/ph1l/ocemr/issues/19
