### ISSUE TITLE
Add Maternity tab

### ISSUE THREAD

**Issue by ph1l** [ocemr/ocemr#7]
<a href="https://github.com/kzcbum"><img src="https://avatars3.githubusercontent.com/u/1439070?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kzcbum](https://github.com/kzcbum)**
_Sat Jul 14 05:29:22 2018_
_Originally opened as https://github.com/ph1l/ocemr/issues/43_

----

To allow for 1 page that tracks all pregnancy basics data, allowing data to be added onto with each subsequent pregnancy, so every "episode" of pregnancy does not require a new page, but this Maternity tab would be updated ongoing moving forward. This could also hold patient's past pregnancy data, as that would be entered at their pre-delivery antenatal care (ANC) visit for any past pregnancies.

This would summarize delivery related data and outcomes. Routine antenatal care visits would be under regular outpatient clinic visits, to allow for lab and med orders and billing per usual workflow. Admissions for labor and delivery would be tracked on paper until discharge, then discharge information to be entered per local standard format into a routine visit, with discharge summary information and meds/billing collected at the end. This would print as a normal clinic visit as their discharge summary.

Will attach sample page layout/data points of this Maternity Tab as an example.

**Comment by ph1l** [comment]
<a href="https://github.com/ph1l"><img src="https://avatars3.githubusercontent.com/u/39502?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ph1l](https://github.com/ph1l)**
_Sat Jul 21 22:51:25 2018_

----

@kzcbum said:

> Will attach sample page layout/data points of this Maternity Tab as an example.

**Comment by ph1l** [comment]
<a href="https://github.com/kzcbum"><img src="https://avatars3.githubusercontent.com/u/1439070?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kzcbum](https://github.com/kzcbum)**
_Fri Jul 27 19:16:12 2018_

----


[Maternity tab mock-up.pdf](https://github.com/ph1l/ocemr/files/2236950/Maternity.tab.mock-up.pdf)

**Comment by ph1l** [comment]
<a href="https://github.com/kzcbum"><img src="https://avatars3.githubusercontent.com/u/1439070?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kzcbum](https://github.com/kzcbum)**
_Fri Jul 27 19:16:41 2018_

----

sorry, don't have way to fix the table using Drive options

**Comment by kzcbum** [comment]
No worries. It's really just so you guys could get a better visualization
of it.

On Nov 4, 2018 7:49 PM, "Philip Freeman" <notifications@github.com> wrote:

<https://github.com/kzcbum> *Comment by kzcbum <https://github.com/kzcbum>*
*Fri Jul 27 19:16:41 2018*
------------------------------

sorry, don't have way to fix the table using Drive options

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ocemr/ocemr/issues/7#issuecomment-435739791>, or mute
the thread

**Comment by ph1l** [comment]
So this is a feature to track only past pregnancies?

**Comment by patfreeman** [comment]
The calendar popup does not support date and time, which we want to track. It looks weird, because the css is not working on it. Needs some skinning.

RE past only: I believe so.

**Comment by kzcbum** [comment]
Tracks past and current moving forward
